### ISSUE TITLE
Release latest version ?

### ISSUE THREAD

**Issue by jarthod** [yourabi/twitter-typeahead-rails#18]
I see the gem is a bit outdated on rubygems: https://rubygems.org/gems/twitter-typeahead-rails
Would you mind releasing the latest version ? :smiley:

**Comment by mauricio-gonzalez** [comment]
+1

**Comment by dflourusso** [comment]
+ 1

**Comment by bosskovic** [comment]
The examples given on http://twitter.github.io/typeahead.js/examples/ do not work with 0.10.5 (version packaged in this gem). It took me too long to figure out that it was not me doing something wrong...

**Comment by seandilda** [comment]
Dittoing bosskovic, I just wasted a half hour on version mismatch issues.

**Comment by redox** [comment]
Beware, the latest version (0.11) is broken with remote sources, I would wait before embedding it in that gem. The issue is here https://github.com/twitter/typeahead.js/issues/1185. The previous documentation can be accessed from here: https://github.com/twitter/typeahead.js/blob/v0.10.5/doc/jquery_typeahead.md

**Comment by yourabi** [comment]
Done
